'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionBBDDRemotaLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoConfiguracionBBDDRemotaLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoConfiguracionBBDDRemotaLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionBBDDRemotaSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoConfiguracionBBDDRemotaSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoConfiguracionBBDDRemotaSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionBBDDLocalLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoConfiguracionBBDDLocalLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoConfiguracionBBDDLocalLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionBBDDLocalSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoConfiguracionBBDDLocalSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoConfiguracionBBDDLocalSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoConfiguracionLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoConfiguracionLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoPruebasLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoPruebasLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoPruebasSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoPruebasSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasCodigoWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasCodigoWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasCodigoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasAbrvWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasAbrvWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasAbrvWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasNombreWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasCodigoTWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasCodigoTWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasCodigoTWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasAbrvTWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasAbrvTWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasAbrvTWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasNombreTWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasNombreTWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasNombreTWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasMuestraTWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasMuestraTWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasMuestraTWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasCodigoMuestraWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasCodigoMuestraWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasCodigoMuestraWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasAbrvMuestraWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasAbrvMuestraWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasAbrvMuestraWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasNombreMuestraWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasNombreMuestraWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasNombreMuestraWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasCodigoMicroWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasCodigoMicroWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasCodigoMicroWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasAbrvMicroWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasAbrvMicroWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasAbrvMicroWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasNombreMicroWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasNombreMicroWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasNombreMicroWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasMuestra2TWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasMuestra2TWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasMuestra2TWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasMuestra3TWidth() As Integer
            Get
                Return CType(Me("DialogoPruebasMuestra3TWidth"),Integer)
            End Get
            Set
                Me("DialogoPruebasMuestra3TWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoMedicosLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoMedicosLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoMedicosLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoMedicosSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoMedicosSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoMedicosSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoMedicosCodigoWidth() As Integer
            Get
                Return CType(Me("DialogoMedicosCodigoWidth"),Integer)
            End Get
            Set
                Me("DialogoMedicosCodigoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoMedicosNombreWidth() As Integer
            Get
                Return CType(Me("DialogoMedicosNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoMedicosNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDestinosLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoDestinosLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoDestinosLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDestinosSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoDestinosSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoDestinosSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDestinosCodigoWidth() As Integer
            Get
                Return CType(Me("DialogoDestinosCodigoWidth"),Integer)
            End Get
            Set
                Me("DialogoDestinosCodigoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDestinosNombreWidth() As Integer
            Get
                Return CType(Me("DialogoDestinosNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoDestinosNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoServiciosLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoServiciosLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoServiciosLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoServiciosSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoServiciosSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoServiciosSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoServiciosCodigoWidth() As Integer
            Get
                Return CType(Me("DialogoServiciosCodigoWidth"),Integer)
            End Get
            Set
                Me("DialogoServiciosCodigoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoServiciosNombreWidth() As Integer
            Get
                Return CType(Me("DialogoServiciosNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoServiciosNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoOrigenesLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoOrigenesLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoOrigenesLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoOrigenesSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoOrigenesSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoOrigenesSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoOrigenesCodigoWidth() As Integer
            Get
                Return CType(Me("DialogoOrigenesCodigoWidth"),Integer)
            End Get
            Set
                Me("DialogoOrigenesCodigoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoOrigenesNombreWidth() As Integer
            Get
                Return CType(Me("DialogoOrigenesNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoOrigenesNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoHCLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoHCLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoHCSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoHCSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCNumeroWidth() As Integer
            Get
                Return CType(Me("DialogoHCNumeroWidth"),Integer)
            End Get
            Set
                Me("DialogoHCNumeroWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCApellidosWidth() As Integer
            Get
                Return CType(Me("DialogoHCApellidosWidth"),Integer)
            End Get
            Set
                Me("DialogoHCApellidosWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCNombreWidth() As Integer
            Get
                Return CType(Me("DialogoHCNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoHCNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCFechaNacimientoWidth() As Integer
            Get
                Return CType(Me("DialogoHCFechaNacimientoWidth"),Integer)
            End Get
            Set
                Me("DialogoHCFechaNacimientoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDiagnosticoLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DialogoDiagnosticoLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DialogoDiagnosticoLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDiagnosticoSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("DialogoDiagnosticoSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("DialogoDiagnosticoSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDiagnosticoCodigoWidth() As Integer
            Get
                Return CType(Me("DialogoDiagnosticoCodigoWidth"),Integer)
            End Get
            Set
                Me("DialogoDiagnosticoCodigoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDiagnosticoNombreWidth() As Integer
            Get
                Return CType(Me("DialogoDiagnosticoNombreWidth"),Integer)
            End Get
            Set
                Me("DialogoDiagnosticoNombreWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property NoCaseSensitive() As Integer
            Get
                Return CType(Me("NoCaseSensitive"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionBBDDRemotaState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoConfiguracionBBDDRemotaState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoConfiguracionBBDDRemotaState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoConfiguracionBBDDLocalState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoConfiguracionBBDDLocalState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoConfiguracionBBDDLocalState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoPruebasState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoPruebasState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoPruebasState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoMedicosState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoMedicosState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoMedicosState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDestinosState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoDestinosState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoDestinosState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoServiciosState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoServiciosState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoServiciosState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoOrigenesState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoOrigenesState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoOrigenesState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoHCState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoHCState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoHCState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DialogoDiagnosticoState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("DialogoDiagnosticoState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("DialogoDiagnosticoState") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LibOmega.My.MySettings
            Get
                Return Global.LibOmega.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
